name = "server-sg7" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "df.game.naver.com.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "beta.zoom.us.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "zoomgov.socifiles.com.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "api.zoom.us.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "store.zoom.us.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "zoomgov.socifiles.com.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "access.zoominfo.com.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "access.zoom.us.sg7.tokodswara4.my.id"
custom_domain = true
[[routes]]
pattern = "news.microsoft.com.sg7.tokodswara4.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "90eb2f6d-f7c4-4886-ba19-929922787302"
